language: scala

notifications:
  email:
    on_success: never

# See 'project/Version.scala'
scala:
   - 2.11.6

sbt_args: -no-colors -J-Xss2m

script:
  - sbt -jvm-opts travis/jvmopts.compile compile
  - sbt -jvm-opts travis/jvmopts.test test

jdk:
  - oraclejdk8
#  - oraclejdk7
#  - openjdk7

env:
  - secure: "WR6A/9dDUW2MpBE0r/HxRRlxV8WD+buhuaFmZQHKHPH09bwMq8b5VyT15e6qCScg+oDVFIpJURB8ezWGMPh1k0bwyvEUFoDEYQb4FpOXFKj2sWk8k8PMCqP7rLfeUXkVt/76rvWnvQNfxCOQ6h1nUsEpPJBAjDB3H/PDA63leDX46eEVmM6gLqgEjb1koRqnsB42RKDSI6OZmTqd4HMfS/QndbMbpjJBqnzSsp7JBHcHI4HJR2RWkyxT4VuGmwyEe3DyB4R3nKclDwaGg0/eDxhgyqbEcsWZsXzbFZrTX9ACNN597ZPb7bKvfNUfQUO8sCaA7eevUG/MdAwIdmRq03hPutD1eNi4sFGoCFWZWZkxYID4Anz+owRuusp0dowypKykjnNhqlnQw2b0pFomDBhziowECNbZtINF0qE32Wq0IFHfmdF80tqfVEfrvlEsqce5RUKAG813uvx9LqiQ++9EszRbC/7Y8QeJkoG3dOZXUkNjeg24jW/+2MRsLLdW5iY+/vbhy449+SaRMS/li4RFDDOfJ/emnNYc44dK87nejnifPNgGnfTrz9QwHPKG9pYkQamWQ1o23DNE1lLw7dCRHHz4xLBVM/k8FS66yFkbijWxk20c0NJZ1nNYd+4OJ3k2bzwsCC92yOR+bOJSWWTibCiu6UV5efBxu5WW7+A="

before_install:
  # JDK fix
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - cat /etc/hosts # optionally check the content *after*
  - cd ..

  # Verilator
  #- sudo apt-get install git make autoconf g++ flex bison -y  # First time prerequisites
  #- git clone http://git.veripool.org/git/verilator   # Only first time
  #- unset VERILATOR_ROOT  # For bash
  #- cd verilator
  #- git pull        # Make sure we're up-to-date
  #- git checkout verilator_3_916
  #- autoconf        # Create ./configure script
  #- ./configure
  #- make -j$(nproc)
  #- sudo make install
  #- cd ..

  - cd VexRiscv
  - curl -T README.md -udolu1990:$BINTRAY_KEY https://api.bintray.com/content/spinalhdl/VexRiscv/test/0.0.4/README.md
  - curl -X POST -udolu1990:$BINTRAY_KEY https://api.bintray.com/content/spinalhdl/VexRiscv/test/0.0.4/publish
  - sbt compile


before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
